### PR TITLE
Updates to data language on front page

### PR DESCRIPTION
**Pull request by BGranberg**
Done for the day...ready to merge

### CODE REVIEW

**Comment by BGranberg** [comment]
Ready to merge....mostly work to the front page

**Comment by BGranberg** [comment]
oops...meant to just comment sorry for the unnecessary/unintended close

**Comment by steveoh** [comment]
This looks good. I think we should add the class **grid__col--s-1-of-2** to the pictures on the data section. It will look better on mobile. Will you do that and then I will accept?

**Comment by steveoh** [comment]
I do not like that we are scaling images with html attributes like 

```html
height="75" width="75"
```
this is a bad practice. The image should be 75x75 if that is what size we want them to be. We are wasting bandwidth and slowing down the page load by downsizing a bigger image.

**Comment by steveoh** [comment]
i took care of it.

**Pull request closed without merging**
